module.exports.awardTable = [
  '<table>',
  '<caption style="text-align:left">',
  '<big><a href="/wiki/1927_in_film" title="1927 in film">1927</a>',
  '/<a href="/wiki/1928_in_film" title="1928 in film">28</a>',
  '<sup class="reference" id="ref_Y27-29"><a href="#endnote_Y27-29">[A]</a></sup></big>',
  '<a href="/wiki/1st_Academy_Awards" title="1st Academy Awards">(1st)</a>',
  '</caption>',
  '<tbody><tr style="background:#bebebe">',
  '<th style="width:33%;">Film</th>',
  '<th style="width:33%;">Production Company(s)</th>',
  '<th style="width:33%;">Producer(s)</th>',
  '</tr>',
  '<tr style="background:#FAEB86">',
  '<td><i><a href="/wiki/Wings_(1927_film)" title="Wings (1927 film)">Wings</a></i></td>',
  '<td><a href="/wiki/Paramount_Pictures" title="Paramount Pictures">Paramount</a>, <a href="/wiki/Famous_Players-Lasky" title="Famous Players-Lasky">Famous Players-Lasky</a></td>',
  '<td><a href="/wiki/Lucien_Hubbard" title="Lucien Hubbard">Lucien Hubbard</a></td>',
  '</tr>',
  '<tr>',
  '<td><i><a href="/wiki/The_Racket_(1928_film)" title="The Racket (1928 film)">The Racket</a></i></td>',
  '<td>Caddo, Paramount</td>',
  '<td><a href="/wiki/Howard_Hughes" title="Howard Hughes">Howard Hughes</a></td>',
  '</tr>',
  '<tr style="background:#eee;">',
  '<td><i><a href="/wiki/Seventh_Heaven_(1927_film)" title="Seventh Heaven (1927 film)" class="mw-redirect">Seventh Heaven</a></i></td>',
  '<td><a href="/wiki/Fox_Film" title="Fox Film">Fox</a></td>',
  '<td><a href="/wiki/William_Fox_(producer)" title="William Fox (producer)">William Fox</a></td>',
  '</tr>',
  '</tbody>',
  '</table>',
].join('');

module.exports.infoTable = [
  '<div>',
  '<h1 id="firstHeading" class="firstHeading" lang="en"><i>Wings</i> (1927 film)</h1>',
  '<table class="infobox vevent" style="width:22em;font-size:90%;">',
  '<tbody><tr>',
  '<th colspan="2" class="summary" style="text-align:center;font-size:125%;font-weight:bold;font-size:110%;font-style:italic;">Wings</th>',
  '</tr>',
  '<tr>',
  '<td colspan="2" style="text-align:center"><a href="/wiki/File:Wings_poster.jpg" class="image"><img alt="Wings poster.jpg" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/67/Wings_poster.jpg/220px-Wings_poster.jpg" width="220" height="333" class="thumbborder" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/67/Wings_poster.jpg/330px-Wings_poster.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/67/Wings_poster.jpg/440px-Wings_poster.jpg 2x" data-file-width="990" data-file-height="1500"></a>',
  '<div style="font-size:95%;padding:0.35em 0.35em 0.25em;line-height:1.25em;">Film poster</div>',
  '</td>',
  '</tr>',
  '<tr>',
  '<th scope="row" style="text-align:left;white-space:nowrap;padding-right:0.65em;">Distributed by</th>',
  '<td style="line-height:1.3em;"><a href="/wiki/Paramount_Pictures" title="Paramount Pictures">Paramount Pictures</a></td>',
  '</tr>',
  '<tr>',
  '<th scope="row" style="text-align:left;white-space:nowrap;padding-right:0.65em;">Language</th>',
  '<td style="line-height:1.3em;"><a href="/wiki/Silent_film" title="Silent film">Silent film</a><br>',
  'English intertitles</td>',
  '</tr>',
  '<tr>',
  '<th scope="row" style="text-align:left;white-space:nowrap;padding-right:0.65em;">Budget</th>',
  '<td style="line-height:1.3em;"><a href="/wiki/United_States_dollar" title="United States dollar">US$</a>2 million<sup id="cite_ref-Silent_Era_5-0" class="reference"><a href="#cite_note-Silent_Era-5"><span>[</span>4<span>]</span></a></sup></td>',
  '</tr>',
  '</tbody>',
  '<table>',
  '</div>',
].join('');

